[package]
name = "mplbubblegumnifs"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "mplbubblegumnifs"
crate-type = ["cdylib"]

[dependencies]
solana-sdk = "2.2.0"
solana-program = "2.2.0"
mpl-bubblegum = "1.4.0"
rustler = "0.36.1"
mpl-core = "0.9.1"
